
services:
  lcla_vlm:
    build:
      context: .
      dockerfile: Dockerfile.noetic_vlm
    image: ros_noetic:lcla
    container_name: lcla_vlm
    network_mode: host
    ipc: host
    environment:
      ROS_MASTER_URI: "http://192.168.0.114:11311"
      ROS_IP: "192.168.0.177"
      PYTHONUNBUFFERED: 1
      PULSE_SERVER: "unix:/run/user/1000/pulse/native"
    devices:
      - /dev/snd:/dev/snd
    volumes:
      - /home/nitesh/workspace/robotvlm:/workspace/robotvlm:ro
      - /home/nitesh/IsaacSim5/IsaacLab:/workspace/IsaacLab:rw
      - ./scripts:/workspace/scripts:rw
      - /run/user/1000/pulse:/run/user/1000/pulse
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    working_dir: /workspace
    command: ["bash", "-lc", "source /opt/ros/noetic/setup.bash && python3 /workspace/IsaacLab/vlm_test.py"]

    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
